### ISSUE TITLE
zo si uanai

### ISSUE THREAD

**Issue by lagleki** [guskant/gerna_cipra#2]
pe'i cfila i mu'a lu ma si valsi li'u se gentufa gi'e cupra zoi vric
([ma si] [CU {valsi VAU}] IAU) 

vric
i lo nu setca zo i lo pamoi pagbu cu vimcu lo jai se srera

**Comment by guskant** [comment]
ie ki'e la gleki mi puzi stika tedi'o lo ve farvi xi 0.9999
