### ISSUE TITLE
ma smuni lu mi je ce'e do li'u

### ISSUE THREAD

**Issue by lagleki** [guskant/gerna_cipra#4]
i ca ti zo ce'e cmavo ma'oi bo i ku'i ma prali i ma ka'e smuni lo simsa be ke mu'a lu mi je ce'e do li'u

**Comment by guskant** [comment]
ma'i la zantufa mi djica lo nu vimcu zo ce'e i ku'i tezu'e lo nu genturfa'i lo se pagbu be zo ce'e be'o noi catni cu curmi lo nu zo ce'e nenri lo gerna i no da smuni lu mi je ce'e do li'u
