### ISSUE TITLE
{([{ro BOI} {mo <ge mo (¹gi mo¹) GIhI>} KU] VAU) }

### ISSUE THREAD

**Issue by lagleki** [guskant/gerna_cipra#5]
pe'i na drani se gentufa

**Comment by guskant** [comment]
ku'i pe'i drani i ma drani ma'i do

**Comment by lagleki** [comment]
lo catni cu stidi tu'a zoi zoi 

```
([{<ro BOI> mo KU} CU] [ge {mo VAU} gi {mo VAU} VAU]) 
```

zoi

**Comment by guskant** [comment]
la'e di'u cu se krinu lo nu lo catni gerna cu te frica ma'oi GUhA ma'oi GA i ma'i la zantufa lo cmavo be ma'oi GUhA cu na'e se nitcu jecu ku'i binxo lo cmavo be ma'oi GA i lu ro mo cu ge mo gi mo li'u ja lu ro mo ge cu mo gi mo li'u cu se stura lo simsa be tu'a lo catni gerna sei ku'i na'e dunli
